DROP TABLE if exists kdlab.dim_driver;
CREATE TABLE kdlab.dim_driver
(
driver_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE az64
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,policy_id INTEGER NOT NULL ENCODE az64
,systemid INTEGER NOT NULL ENCODE RAW
,currentflg INTEGER NOT NULL ENCODE az64
,bookdt DATE NOT NULL ENCODE az64
,transactioneffectivedt DATE NOT NULL ENCODE az64
,policy_uniqueid INTEGER NOT NULL ENCODE az64
,drivernumber INTEGER NOT NULL ENCODE az64
,driver_uniqueid VARCHAR(255) NOT NULL ENCODE lzo
,spinndriver_id VARCHAR(255) NOT NULL ENCODE lzo
,status VARCHAR(255) NOT NULL ENCODE lzo
,firstname VARCHAR(255) NOT NULL ENCODE lzo
,lastname VARCHAR(255) NOT NULL ENCODE lzo
,licensenumber VARCHAR(255) NOT NULL ENCODE lzo
,licensedt TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,driverinfocd VARCHAR(255) NOT NULL ENCODE lzo
,drivertypecd VARCHAR(255) NOT NULL ENCODE lzo
,driverstatuscd VARCHAR(255) NOT NULL ENCODE lzo
,licensedstateprovcd VARCHAR(255) NOT NULL ENCODE lzo
,relationshiptoinsuredcd VARCHAR(255) NOT NULL ENCODE lzo
,scholasticdiscountind VARCHAR(255) NOT NULL ENCODE lzo
,mvrrequestind VARCHAR(255) NOT NULL ENCODE lzo
,mvrstatus VARCHAR(255) NOT NULL ENCODE lzo
,mvrstatusdt TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,maturedriverind VARCHAR(255) NOT NULL ENCODE lzo
,drivertrainingind VARCHAR(255) NOT NULL ENCODE lzo
,gooddriverind VARCHAR(255) NOT NULL ENCODE lzo
,accidentpreventioncoursecompletiondt TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,drivertrainingcompletiondt TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,accidentpreventioncourseind VARCHAR(255) NOT NULL ENCODE lzo
,scholasticcertificationdt TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,activemilitaryind VARCHAR(255) NOT NULL ENCODE lzo
,permanentlicenseind VARCHAR(255) NOT NULL ENCODE lzo
,newtostateind VARCHAR(255) NOT NULL ENCODE lzo
,persontypecd VARCHAR(255) NOT NULL ENCODE lzo
,gendercd VARCHAR(255) NOT NULL ENCODE lzo
,birthdt TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,maritalstatuscd VARCHAR(255) NOT NULL ENCODE lzo
,occupationclasscd VARCHAR(255) NOT NULL ENCODE lzo
,positiontitle VARCHAR(255) NOT NULL ENCODE lzo
,currentresidencecd VARCHAR(255) NOT NULL ENCODE lzo
,civilservantind VARCHAR(255) NOT NULL ENCODE lzo
,retiredind VARCHAR(255) NOT NULL ENCODE lzo
,newteenexpirationdt DATE NOT NULL ENCODE az64
,attachedvehicleref VARCHAR(255) NOT NULL ENCODE lzo
,viol_pointschargedterm INTEGER NOT NULL ENCODE az64
,acci_pointschargedterm INTEGER NOT NULL ENCODE az64
,susp_pointschargedterm INTEGER NOT NULL ENCODE az64
,other_pointschargedterm INTEGER NOT NULL ENCODE az64
,gooddriverpoints_chargedterm INTEGER NOT NULL ENCODE az64
,sr22feeind VARCHAR(4) NOT NULL ENCODE lzo
,maturecertificationdt TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,agefirstlicensed INTEGER NOT NULL ENCODE az64
,PRIMARY KEY (driver_id)
)
DISTSTYLE KEY
DISTKEY (systemid)
SORTKEY (
systemid
)
;

drop table if exists kdlab.dim_product;
CREATE TABLE kdlab.dim_product
(
product_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE RAW
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,product_uniqueid VARCHAR(100) NOT NULL ENCODE lzo
,carriergroupcd VARCHAR(100) NOT NULL ENCODE lzo
,description VARCHAR(2000) NOT NULL ENCODE lzo
,subtypecd VARCHAR(100) NOT NULL ENCODE lzo
,productversion VARCHAR(24) NOT NULL ENCODE lzo
,name VARCHAR(64) NOT NULL ENCODE lzo
,producttypecd VARCHAR(32) NOT NULL ENCODE lzo
,carriercd VARCHAR(8) NOT NULL ENCODE lzo
,isselect INTEGER NOT NULL ENCODE az64
,linecd VARCHAR(32) NOT NULL ENCODE lzo
,altsubtypecd VARCHAR(32) NOT NULL ENCODE lzo
,subtypeshortdesc VARCHAR(64) NOT NULL ENCODE lzo
,subtypefulldesc VARCHAR(64) NOT NULL ENCODE lzo
,policynumberprefix VARCHAR(3) NOT NULL ENCODE lzo
,startdt DATE ENCODE az64
,stopdt DATE ENCODE az64
,renewalstartdt DATE ENCODE az64
,renewalstopdt DATE ENCODE az64
,statecd VARCHAR(2) NOT NULL ENCODE lzo
,contract VARCHAR(8) NOT NULL ENCODE lzo
,lob VARCHAR(8) NOT NULL ENCODE lzo
,propertyform VARCHAR(8) NOT NULL ENCODE lzo
,prerenewaldays INTEGER NOT NULL ENCODE az64
,autorenewaldays INTEGER NOT NULL ENCODE az64
,mgafeeplancd VARCHAR(24) NOT NULL ENCODE lzo
,tpafeeplancd VARCHAR(24) NOT NULL ENCODE lzo
,PRIMARY KEY (product_id)
)
DISTSTYLE ALL
SORTKEY (
product_id
)
;

drop table if exists kdlab.dim_building;
CREATE TABLE kdlab.dim_building
(
building_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE az64
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,policy_id INTEGER NOT NULL ENCODE az64
,systemid INTEGER NOT NULL ENCODE RAW
,currentflg INTEGER NOT NULL ENCODE az64
,bookdt DATE NOT NULL ENCODE az64
,transactioneffectivedt DATE NOT NULL ENCODE az64
,policy_uniqueid INTEGER NOT NULL ENCODE az64
,risk_uniqueid VARCHAR(255) NOT NULL ENCODE lzo
,bldgnumber INTEGER NOT NULL ENCODE az64
,building_uniqueid VARCHAR(525) NOT NULL ENCODE lzo
,spinnbuilding_id VARCHAR(255) NOT NULL ENCODE lzo
,status VARCHAR(255) NOT NULL ENCODE lzo
,stateprovcd VARCHAR(255) NOT NULL ENCODE lzo
,county VARCHAR(255) NOT NULL ENCODE lzo
,postalcode VARCHAR(255) NOT NULL ENCODE lzo
,city VARCHAR(255) NOT NULL ENCODE lzo
,addr1 VARCHAR(255) NOT NULL ENCODE lzo
,addr2 VARCHAR(255) NOT NULL ENCODE lzo
,businesscategory VARCHAR(255) NOT NULL ENCODE lzo
,businessclass VARCHAR(255) NOT NULL ENCODE lzo
,constructioncd VARCHAR(255) NOT NULL ENCODE lzo
,roofcd VARCHAR(255) NOT NULL ENCODE lzo
,yearbuilt INTEGER NOT NULL ENCODE az64
,sqft INTEGER NOT NULL ENCODE az64
,stories INTEGER NOT NULL ENCODE az64
,units INTEGER NOT NULL ENCODE az64
,occupancycd VARCHAR(255) NOT NULL ENCODE lzo
,protectionclass VARCHAR(255) NOT NULL ENCODE lzo
,territorycd VARCHAR(255) NOT NULL ENCODE lzo
,buildinglimit INTEGER NOT NULL ENCODE az64
,contentslimit INTEGER NOT NULL ENCODE az64
,valuationmethod VARCHAR(255) NOT NULL ENCODE lzo
,inflationguardpct INTEGER NOT NULL ENCODE az64
,ordinanceorlawind VARCHAR(255) NOT NULL ENCODE lzo
,scheduledpremiummod INTEGER NOT NULL ENCODE az64
,windhailexclusion VARCHAR(255) NOT NULL ENCODE lzo
,covalimit INTEGER NOT NULL ENCODE az64
,covblimit INTEGER NOT NULL ENCODE az64
,covclimit INTEGER NOT NULL ENCODE az64
,covdlimit INTEGER NOT NULL ENCODE az64
,covelimit INTEGER NOT NULL ENCODE az64
,covflimit INTEGER NOT NULL ENCODE az64
,allperilded VARCHAR(255) NOT NULL ENCODE lzo
,burglaryalarmtype VARCHAR(255) NOT NULL ENCODE lzo
,firealarmtype VARCHAR(255) NOT NULL ENCODE lzo
,covblimitincluded INTEGER NOT NULL ENCODE az64
,covblimitincrease INTEGER NOT NULL ENCODE az64
,covclimitincluded INTEGER NOT NULL ENCODE az64
,covclimitincrease INTEGER NOT NULL ENCODE az64
,covdlimitincluded INTEGER NOT NULL ENCODE az64
,covdlimitincrease INTEGER NOT NULL ENCODE az64
,ordinanceorlawpct INTEGER NOT NULL ENCODE az64
,neighborhoodcrimewatchind VARCHAR(255) NOT NULL ENCODE lzo
,employeecreditind VARCHAR(255) NOT NULL ENCODE lzo
,multipolicyind VARCHAR(255) NOT NULL ENCODE lzo
,homewarrantycreditind VARCHAR(255) NOT NULL ENCODE lzo
,yearoccupied INTEGER NOT NULL ENCODE az64
,yearpurchased INTEGER NOT NULL ENCODE az64
,typeofstructure VARCHAR(255) NOT NULL ENCODE lzo
,feettofirehydrant INTEGER NOT NULL ENCODE az64
,numberoffamilies INTEGER NOT NULL ENCODE az64
,milesfromfirestation INTEGER NOT NULL ENCODE az64
,rooms INTEGER NOT NULL ENCODE az64
,roofpitch VARCHAR(255) NOT NULL ENCODE lzo
,firedistrict VARCHAR(255) NOT NULL ENCODE lzo
,sprinklersystem VARCHAR(255) NOT NULL ENCODE lzo
,fireextinguisherind VARCHAR(255) NOT NULL ENCODE lzo
,kitchenfireextinguisherind VARCHAR(255) NOT NULL ENCODE lzo
,deadboltind VARCHAR(255) NOT NULL ENCODE lzo
,gatedcommunityind VARCHAR(255) NOT NULL ENCODE lzo
,centralheatingind VARCHAR(255) NOT NULL ENCODE lzo
,foundation VARCHAR(255) NOT NULL ENCODE lzo
,wiringrenovation VARCHAR(255) NOT NULL ENCODE lzo
,wiringrenovationcompleteyear VARCHAR(255) NOT NULL ENCODE lzo
,plumbingrenovation VARCHAR(255) NOT NULL ENCODE lzo
,heatingrenovation VARCHAR(255) NOT NULL ENCODE lzo
,plumbingrenovationcompleteyear VARCHAR(255) NOT NULL ENCODE lzo
,exteriorpaintrenovation VARCHAR(255) NOT NULL ENCODE lzo
,heatingrenovationcompleteyear VARCHAR(255) NOT NULL ENCODE lzo
,circuitbreakersind VARCHAR(255) NOT NULL ENCODE lzo
,copperwiringind VARCHAR(255) NOT NULL ENCODE lzo
,exteriorpaintrenovationcompleteyear VARCHAR(255) NOT NULL ENCODE lzo
,copperpipesind VARCHAR(255) NOT NULL ENCODE lzo
,earthquakeretrofitind VARCHAR(255) NOT NULL ENCODE lzo
,primaryfuelsource VARCHAR(255) NOT NULL ENCODE lzo
,secondaryfuelsource VARCHAR(255) NOT NULL ENCODE lzo
,usagetype VARCHAR(255) NOT NULL ENCODE lzo
,homegardcreditind VARCHAR(255) NOT NULL ENCODE lzo
,multipolicynumber VARCHAR(255) NOT NULL ENCODE lzo
,localfirealarmind VARCHAR(255) NOT NULL ENCODE lzo
,numlosses INTEGER NOT NULL ENCODE az64
,covalimitincrease INTEGER NOT NULL ENCODE az64
,covalimitincluded INTEGER NOT NULL ENCODE az64
,monthsrentedout INTEGER NOT NULL ENCODE az64
,roofreplacement VARCHAR(255) NOT NULL ENCODE lzo
,safeguardplusind VARCHAR(255) NOT NULL ENCODE lzo
,covelimitincluded INTEGER NOT NULL ENCODE az64
,roofreplacementcompleteyear VARCHAR(255) NOT NULL ENCODE lzo
,covelimitincrease INTEGER NOT NULL ENCODE az64
,owneroccupiedunits INTEGER NOT NULL ENCODE az64
,tenantoccupiedunits INTEGER NOT NULL ENCODE az64
,replacementcostdwellingind VARCHAR(255) NOT NULL ENCODE lzo
,feettopropertyline VARCHAR(255) NOT NULL ENCODE lzo
,galvanizedpipeind VARCHAR(255) NOT NULL ENCODE lzo
,workerscompinservant INTEGER NOT NULL ENCODE az64
,workerscompoutservant INTEGER NOT NULL ENCODE az64
,liabilityterritorycd VARCHAR(255) NOT NULL ENCODE lzo
,premisesliabilitymedpayind VARCHAR(255) NOT NULL ENCODE lzo
,relatedprivatestructureexclusion VARCHAR(255) NOT NULL ENCODE lzo
,vandalismexclusion VARCHAR(255) NOT NULL ENCODE lzo
,vandalismind VARCHAR(255) NOT NULL ENCODE lzo
,roofexclusion VARCHAR(255) NOT NULL ENCODE lzo
,expandedreplacementcostind VARCHAR(255) NOT NULL ENCODE lzo
,replacementvalueind VARCHAR(255) NOT NULL ENCODE lzo
,otherpolicynumber1 VARCHAR(255) NOT NULL ENCODE lzo
,otherpolicynumber2 VARCHAR(255) NOT NULL ENCODE lzo
,otherpolicynumber3 VARCHAR(255) NOT NULL ENCODE lzo
,primarypolicynumber VARCHAR(255) NOT NULL ENCODE lzo
,otherpolicynumbers VARCHAR(255) NOT NULL ENCODE lzo
,reportedfirehazardscore VARCHAR(255) NOT NULL ENCODE lzo
,firehazardscore VARCHAR(255) NOT NULL ENCODE lzo
,reportedsteepslopeind VARCHAR(255) NOT NULL ENCODE lzo
,steepslopeind VARCHAR(255) NOT NULL ENCODE lzo
,reportedhomereplacementcost INTEGER NOT NULL ENCODE az64
,reportedprotectionclass VARCHAR(255) NOT NULL ENCODE lzo
,earthquakezone VARCHAR(255) NOT NULL ENCODE lzo
,mmiscore VARCHAR(255) NOT NULL ENCODE lzo
,homeinspectiondiscountind VARCHAR(255) NOT NULL ENCODE lzo
,ratingtier VARCHAR(255) NOT NULL ENCODE lzo
,soiltypecd VARCHAR(255) NOT NULL ENCODE lzo
,reportedfirelineassessment VARCHAR(255) NOT NULL ENCODE lzo
,aaisfireprotectionclass VARCHAR(255) NOT NULL ENCODE lzo
,inspectionscore VARCHAR(255) NOT NULL ENCODE lzo
,annualrents INTEGER NOT NULL ENCODE az64
,pitchofroof VARCHAR(255) NOT NULL ENCODE lzo
,totallivingsqft INTEGER NOT NULL ENCODE az64
,parkingsqft INTEGER NOT NULL ENCODE az64
,parkingtype VARCHAR(255) NOT NULL ENCODE lzo
,retrofitcompleted VARCHAR(255) NOT NULL ENCODE lzo
,numpools VARCHAR(255) NOT NULL ENCODE lzo
,fullyfenced VARCHAR(255) NOT NULL ENCODE lzo
,divingboard VARCHAR(255) NOT NULL ENCODE lzo
,gym VARCHAR(255) NOT NULL ENCODE lzo
,freeweights VARCHAR(255) NOT NULL ENCODE lzo
,wirefencing VARCHAR(255) NOT NULL ENCODE lzo
,otherrecreational VARCHAR(255) NOT NULL ENCODE lzo
,otherrecreationaldesc VARCHAR(255) NOT NULL ENCODE lzo
,healthinspection VARCHAR(255) NOT NULL ENCODE lzo
,healthinspectiondt TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,healthinspectioncited VARCHAR(255) NOT NULL ENCODE lzo
,priordefectrepairs VARCHAR(255) NOT NULL ENCODE lzo
,msbreconstructionestimate VARCHAR(255) NOT NULL ENCODE lzo
,biindemnityperiod VARCHAR(255) NOT NULL ENCODE lzo
,equipmentbreakdown VARCHAR(255) NOT NULL ENCODE lzo
,moneysecurityonpremises VARCHAR(255) NOT NULL ENCODE lzo
,moneysecurityoffpremises VARCHAR(255) NOT NULL ENCODE lzo
,waterbackupsump VARCHAR(255) NOT NULL ENCODE lzo
,sprinkleredbuildings VARCHAR(255) NOT NULL ENCODE lzo
,surveillancecams VARCHAR(255) NOT NULL ENCODE lzo
,gatedcomplexkeyaccess VARCHAR(255) NOT NULL ENCODE lzo
,eqretrofit VARCHAR(255) NOT NULL ENCODE lzo
,unitsperbuilding VARCHAR(255) NOT NULL ENCODE lzo
,numstories VARCHAR(255) NOT NULL ENCODE lzo
,constructionquality VARCHAR(255) NOT NULL ENCODE lzo
,burglaryrobbery VARCHAR(255) NOT NULL ENCODE lzo
,nfpaclassification VARCHAR(255) NOT NULL ENCODE lzo
,areasofcoverage VARCHAR(255) NOT NULL ENCODE lzo
,codetector VARCHAR(255) NOT NULL ENCODE lzo
,smokedetector VARCHAR(255) NOT NULL ENCODE lzo
,smokedetectorinspectind VARCHAR(255) NOT NULL ENCODE lzo
,waterheatersecured VARCHAR(255) NOT NULL ENCODE lzo
,boltedorsecured VARCHAR(255) NOT NULL ENCODE lzo
,softstorycripple VARCHAR(255) NOT NULL ENCODE lzo
,seniorhousingpct VARCHAR(255) NOT NULL ENCODE lzo
,designatedseniorhousing VARCHAR(255) NOT NULL ENCODE lzo
,studenthousingpct VARCHAR(255) NOT NULL ENCODE lzo
,designatedstudenthousing VARCHAR(255) NOT NULL ENCODE lzo
,priorlosses INTEGER NOT NULL ENCODE az64
,tenantevictions VARCHAR(255) NOT NULL ENCODE lzo
,vacancyrateexceed VARCHAR(255) NOT NULL ENCODE lzo
,seasonalrentals VARCHAR(255) NOT NULL ENCODE lzo
,condoinsuingagmt VARCHAR(255) NOT NULL ENCODE lzo
,gasvalve VARCHAR(255) NOT NULL ENCODE lzo
,owneroccupiedpct VARCHAR(255) NOT NULL ENCODE lzo
,restaurantname VARCHAR(255) NOT NULL ENCODE lzo
,hoursofoperation VARCHAR(255) NOT NULL ENCODE lzo
,restaurantsqft INTEGER NOT NULL ENCODE az64
,seatingcapacity INTEGER NOT NULL ENCODE az64
,annualgrosssales INTEGER NOT NULL ENCODE az64
,seasonalorclosed VARCHAR(255) NOT NULL ENCODE lzo
,barcocktaillounge VARCHAR(255) NOT NULL ENCODE lzo
,liveentertainment VARCHAR(255) NOT NULL ENCODE lzo
,beerwinegrosssales VARCHAR(255) NOT NULL ENCODE lzo
,distilledspiritsserved VARCHAR(255) NOT NULL ENCODE lzo
,kitchendeepfryer VARCHAR(255) NOT NULL ENCODE lzo
,solidfuelcooking VARCHAR(255) NOT NULL ENCODE lzo
,ansulsystem VARCHAR(255) NOT NULL ENCODE lzo
,ansulannualinspection VARCHAR(255) NOT NULL ENCODE lzo
,tenantnameslist VARCHAR(255) NOT NULL ENCODE lzo
,tenantbusinesstype VARCHAR(255) NOT NULL ENCODE lzo
,tenantglliability VARCHAR(255) NOT NULL ENCODE lzo
,insuredoccupiedportion VARCHAR(255) NOT NULL ENCODE lzo
,valetparking VARCHAR(255) NOT NULL ENCODE lzo
,lessorsqft INTEGER NOT NULL ENCODE az64
,buildingrisknumber INTEGER NOT NULL ENCODE az64
,multipolicyindumbrella VARCHAR(255) NOT NULL ENCODE lzo
,poolind VARCHAR(255) NOT NULL ENCODE lzo
,studsuprenovation VARCHAR(255) NOT NULL ENCODE lzo
,studsuprenovationcompleteyear VARCHAR(255) NOT NULL ENCODE lzo
,multipolicynumberumbrella VARCHAR(255) NOT NULL ENCODE lzo
,rctmsbamt VARCHAR(255) NOT NULL ENCODE lzo
,rctmsbhomestyle VARCHAR(255) NOT NULL ENCODE lzo
,winsoverridenonsmokerdiscount VARCHAR(255) NOT NULL ENCODE lzo
,winsoverrideseniordiscount VARCHAR(255) NOT NULL ENCODE lzo
,itv INTEGER NOT NULL ENCODE az64
,itvdate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,msbreporttype VARCHAR(255) NOT NULL ENCODE lzo
,vandalismdesiredind VARCHAR(255) NOT NULL ENCODE lzo
,woodshakesiding VARCHAR(255) NOT NULL ENCODE lzo
,cseagent VARCHAR(3) NOT NULL ENCODE lzo
,propertymanager VARCHAR(3) NOT NULL ENCODE lzo
,rentersinsurance VARCHAR(3) NOT NULL ENCODE lzo
,waterdetectiondevice VARCHAR(3) NOT NULL ENCODE lzo
,autohomeind VARCHAR(3) NOT NULL ENCODE lzo
,earthquakeumbrellaind VARCHAR(3) NOT NULL ENCODE lzo
,landlordind VARCHAR(3) NOT NULL ENCODE lzo
,lossassessment VARCHAR(16) NOT NULL ENCODE lzo
,gasshutoffind VARCHAR(4) NOT NULL ENCODE lzo
,waterded VARCHAR(16) NOT NULL ENCODE lzo
,serviceline VARCHAR(4) NOT NULL ENCODE lzo
,functionalreplacementcost VARCHAR(4) NOT NULL ENCODE lzo
,milesofstreet VARCHAR(32) NOT NULL ENCODE lzo
,hoaexteriorstructure VARCHAR(3) NOT NULL ENCODE lzo
,retailportiondevelopment VARCHAR(32) NOT NULL ENCODE lzo
,lightindustrialtype VARCHAR(128) NOT NULL ENCODE lzo
,lightindustrialdescription VARCHAR(128) NOT NULL ENCODE lzo
,poolcoveragelimit INTEGER NOT NULL ENCODE az64
,multifamilyresidentialbuildings INTEGER NOT NULL ENCODE az64
,singlefamilydwellings INTEGER NOT NULL ENCODE az64
,annualpayroll INTEGER NOT NULL ENCODE az64
,annualrevenue INTEGER NOT NULL ENCODE az64
,bedsoccupied VARCHAR(16) NOT NULL ENCODE lzo
,emergencylighting VARCHAR(4) NOT NULL ENCODE lzo
,exitsignsposted VARCHAR(4) NOT NULL ENCODE lzo
,fulltimestaff VARCHAR(4) NOT NULL ENCODE lzo
,licensedbeds VARCHAR(10) NOT NULL ENCODE lzo
,numberoffireextinguishers INTEGER NOT NULL ENCODE az64
,otherfireextinguishers VARCHAR(16) NOT NULL ENCODE lzo
,oxygentanks VARCHAR(4) NOT NULL ENCODE lzo
,parttimestaff VARCHAR(4) NOT NULL ENCODE lzo
,smokingpermitted VARCHAR(4) NOT NULL ENCODE lzo
,staffonduty VARCHAR(4) NOT NULL ENCODE lzo
,typeoffireextinguishers VARCHAR(32) NOT NULL ENCODE lzo
,covaddrr_secondaryresidence VARCHAR(3) NOT NULL ENCODE lzo
,covaddrrprem_secondaryresidence NUMERIC(13,2) NOT NULL ENCODE az64
,hodeluxe VARCHAR(3) NOT NULL ENCODE lzo
,latitude NUMERIC(18,12) NOT NULL ENCODE az64
,longitude NUMERIC(18,12) NOT NULL ENCODE az64
,linecd VARCHAR(255) NOT NULL ENCODE lzo
,wuiclass VARCHAR(30) NOT NULL ENCODE lzo
,censusblock VARCHAR(30) NOT NULL ENCODE lzo
,waterriskscore INTEGER NOT NULL ENCODE az64
,landlordlosspreventionservices VARCHAR(5) NOT NULL ENCODE lzo
,enhancedwatercoverage VARCHAR(5) NOT NULL ENCODE lzo
,landlordproperty VARCHAR(5) NOT NULL ENCODE lzo
,liabilityextendedtoothers VARCHAR(5) NOT NULL ENCODE lzo
,lossofuseextendedtime VARCHAR(5) NOT NULL ENCODE lzo
,onpremisestheft INTEGER NOT NULL ENCODE az64
,bedbugmitigation VARCHAR(5) NOT NULL ENCODE lzo
,habitabilityexclusion VARCHAR(5) NOT NULL ENCODE lzo
,wildfirehazardpotential VARCHAR(20) NOT NULL ENCODE lzo
,backupofsewersanddrains INTEGER NOT NULL ENCODE az64
,vegetationsetbackft INTEGER NOT NULL ENCODE az64
,yarddebriscoveragearea INTEGER NOT NULL ENCODE az64
,yarddebriscoveragepercentage VARCHAR(5) NOT NULL ENCODE lzo
,capetrampoline VARCHAR(16) NOT NULL ENCODE lzo
,capepool VARCHAR(16) NOT NULL ENCODE lzo
,roofconditionrating VARCHAR(16) NOT NULL ENCODE lzo
,trampolineind VARCHAR(16) NOT NULL ENCODE lzo
,plumbingmaterial VARCHAR(16) NOT NULL ENCODE lzo
,centralizedheating VARCHAR(16) NOT NULL ENCODE lzo
,firedistrictsubscriptioncode VARCHAR(8) NOT NULL ENCODE lzo
,roofcondition VARCHAR(20) NOT NULL ENCODE lzo
,PRIMARY KEY (building_id)
)
DISTSTYLE KEY
DISTKEY (systemid)
SORTKEY (
systemid
)
;

drop table if exists kdlab.dim_classification;
CREATE TABLE kdlab.dim_classification
(
class_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE RAW
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,class_code VARCHAR(50) NOT NULL ENCODE lzo
,class_codename VARCHAR(50) NOT NULL ENCODE lzo
,class_codedescription VARCHAR(256) NOT NULL ENCODE lzo
,PRIMARY KEY (class_id)
)
DISTSTYLE ALL
SORTKEY (
class_id
)
;


DROP TABLE IF exists kdlab.dim_coverage;
CREATE TABLE kdlab.dim_coverage
(
coverage_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE RAW
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,cov_code VARCHAR(50) NOT NULL ENCODE lzo
,cov_subcode VARCHAR(50) NOT NULL ENCODE lzo
,cov_asl VARCHAR(5) NOT NULL ENCODE lzo
,cov_subline VARCHAR(5) NOT NULL ENCODE lzo
,PRIMARY KEY (coverage_id)
)
DISTSTYLE ALL
SORTKEY (
coverage_id
)
;


DROP TABLE IF EXISTS kdlab.dim_coveredrisk;
CREATE TABLE IF NOT EXISTS kdlab.dim_coveredrisk
(
coveredrisk_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE az64
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,policy_id INTEGER NOT NULL ENCODE az64
,systemid INTEGER NOT NULL ENCODE RAW
,currentflg INTEGER NOT NULL ENCODE az64
,bookdt DATE NOT NULL ENCODE az64
,transactioneffectivedt DATE NOT NULL ENCODE az64
,policy_uniqueid INTEGER NOT NULL ENCODE az64
,deleted_indicator INTEGER NOT NULL ENCODE az64
,risk_number VARCHAR(10) NOT NULL ENCODE lzo
,risk_type VARCHAR(255) NOT NULL ENCODE lzo
,risk_uniqueid VARCHAR(100) NOT NULL ENCODE lzo
,coveredrisk_uniqueid VARCHAR(500) NOT NULL ENCODE lzo
,PRIMARY KEY (coveredrisk_id)
)
DISTSTYLE KEY
DISTKEY (systemid)
SORTKEY (
systemid
)
;

DROP TABLE IF exists kdlab.dim_deductible;
CREATE TABLE kdlab.dim_deductible
(
deductible_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE RAW
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,cov_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,cov_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,PRIMARY KEY (deductible_id)
)
DISTSTYLE ALL
SORTKEY (
deductible_id
)
;


DROP TABLE IF EXISTS kdlab.dim_limit;
CREATE TABLE kdlab.dim_limit
(
limit_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE RAW
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,cov_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,cov_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,cov_limit1_value NUMERIC(13,2) NOT NULL ENCODE az64
,cov_limit2_value NUMERIC(13,2) NOT NULL ENCODE az64
,PRIMARY KEY (limit_id)
)
DISTSTYLE ALL
SORTKEY (
limit_id
)
;


DROP TABLE IF EXISTS kdlab.dim_producer;
CREATE TABLE kdlab.dim_producer
(
producer_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY ( 0, 1 ) ENCODE RAW
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,producer_uniqueid VARCHAR(20) NOT NULL ENCODE lzo
,valid_fromdate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,valid_todate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,record_version INTEGER NOT NULL ENCODE az64
,iscurrent INTEGER NOT NULL ENCODE az64
,producer_number VARCHAR(20) NOT NULL ENCODE lzo
,producer_name VARCHAR(255) NOT NULL ENCODE lzo
,licenseno VARCHAR(255) NOT NULL ENCODE lzo
,agency_type VARCHAR(11) NOT NULL ENCODE lzo
,address VARCHAR(510) NOT NULL ENCODE lzo
,city VARCHAR(80) NOT NULL ENCODE lzo
,state_cd VARCHAR(5) NOT NULL ENCODE lzo
,zip VARCHAR(10) NOT NULL ENCODE lzo
,phone VARCHAR(20) NOT NULL ENCODE lzo
,fax VARCHAR(15) NOT NULL ENCODE lzo
,email VARCHAR(255) NOT NULL ENCODE lzo
,agency_group VARCHAR(255) NOT NULL ENCODE lzo
,national_name VARCHAR(255) NOT NULL ENCODE lzo
,national_code VARCHAR(20) NOT NULL ENCODE lzo
,territory VARCHAR(50) NOT NULL ENCODE lzo
,territory_manager VARCHAR(50) NOT NULL ENCODE lzo
,dba VARCHAR(255) NOT NULL ENCODE lzo
,producer_status VARCHAR(10) NOT NULL ENCODE lzo
,commission_master VARCHAR(20) NOT NULL ENCODE lzo
,reporting_master VARCHAR(20) NOT NULL ENCODE lzo
,pn_appointment_date DATE NOT NULL ENCODE az64
,profit_sharing_master VARCHAR(20) NOT NULL ENCODE lzo
,producer_master VARCHAR(20) NOT NULL ENCODE lzo
,recognition_tier VARCHAR(100) NOT NULL ENCODE lzo
,rmaddress VARCHAR(100) NOT NULL ENCODE lzo
,rmcity VARCHAR(50) NOT NULL ENCODE lzo
,rmstate VARCHAR(25) NOT NULL ENCODE lzo
,rmzip VARCHAR(25) NOT NULL ENCODE lzo
,new_business_term_date DATE NOT NULL ENCODE az64
,PRIMARY KEY (producer_id)
)
DISTSTYLE KEY
DISTKEY (producer_uniqueid)
SORTKEY (
producer_uniqueid
)
;

DROP TABLE IF EXISTS kdlab.dim_risk_coverage;
CREATE TABLE kdlab.dim_risk_coverage
(
coveredrisk_id INTEGER NOT NULL ENCODE az64
,loaddate TIMESTAMP WITHOUT TIME ZONE ENCODE az64
,policy_id INTEGER NOT NULL ENCODE az64
,systemid INTEGER NOT NULL ENCODE RAW
,currentflg INTEGER NOT NULL ENCODE az64
,bookdt DATE NOT NULL ENCODE az64
,transactioneffectivedt DATE NOT NULL ENCODE az64
,policy_uniqueid INTEGER NOT NULL ENCODE az64
,risk_uniqueid VARCHAR(100) NOT NULL ENCODE lzo
,cova_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,cova_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,cova_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,cova_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,cova_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,covb_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,covb_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,covb_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,covb_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,covb_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,covc_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,covc_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,covc_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,covc_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,covc_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,covd_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,covd_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,covd_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,covd_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,covd_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,cove_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,cove_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,cove_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,cove_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,cove_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,bedbug_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,bedbug_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,bedbug_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,bedbug_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,bedbug_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,bolaw_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,bolaw_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,bolaw_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,bolaw_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,bolaw_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,coc_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,coc_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,coc_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,coc_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,coc_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,eqpbk_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,eqpbk_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,eqpbk_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,eqpbk_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,eqpbk_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,fraud_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,fraud_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,fraud_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,fraud_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,fraud_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,h051st0_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,h051st0_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,h051st0_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,h051st0_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,h051st0_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,ho5_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,ho5_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,ho5_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,ho5_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,ho5_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,incb_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,incb_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,incb_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,incb_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,incb_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,incc_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,incc_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,incc_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,incc_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,incc_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,lac_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,lac_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,lac_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,lac_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,lac_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,medpay_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,medpay_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,medpay_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,medpay_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,medpay_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,occupationdiscount_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,occupationdiscount_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,occupationdiscount_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,occupationdiscount_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,occupationdiscount_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,olt_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,olt_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,olt_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,olt_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,olt_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,pihom_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,pihom_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,pihom_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,pihom_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,pihom_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,pprep_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,pprep_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,pprep_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,pprep_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,pprep_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,prtdvc_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,prtdvc_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,prtdvc_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,prtdvc_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,prtdvc_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,seniordiscount_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,seniordiscount_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,seniordiscount_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,seniordiscount_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,seniordiscount_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,sewer_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,sewer_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,sewer_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,sewer_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,sewer_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,spp_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,spp_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,spp_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,spp_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,spp_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,srorp_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,srorp_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,srorp_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,srorp_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,srorp_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,thefa_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,thefa_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,thefa_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,thefa_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,thefa_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,utldb_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,utldb_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,utldb_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,utldb_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,utldb_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,wcinc_limit1 VARCHAR(255) NOT NULL ENCODE lzo
,wcinc_limit2 VARCHAR(255) NOT NULL ENCODE lzo
,wcinc_deductible1 NUMERIC(13,2) NOT NULL ENCODE az64
,wcinc_deductible2 NUMERIC(13,2) NOT NULL ENCODE az64
,wcinc_fulltermamt NUMERIC(13,2) NOT NULL ENCODE az64
,wcinc_limit1_o VARCHAR(255) NOT NULL ENCODE lzo
,wcinc_limit2_o VARCHAR(255) NOT NULL ENCODE lzo
,wcinc_deductible1_o NUMERIC(13,2) NOT NULL ENCODE az64
,wcinc_deductible2_o NUMERIC(13,2) NOT NULL ENCODE az64
,wcinc_fulltermamt_o NUMERIC(13,2) NOT NULL ENCODE az64
,PRIMARY KEY (coveredrisk_id)
)
DISTKEY (systemid)
SORTKEY (
systemid
)
;

DROP TABLE IF EXISTS kdlab.dim_customer;
CREATE TABLE kdlab.dim_customer
(
customer_id INTEGER ENCODE az64
,loaddate TIMESTAMP WITHOUT TIME ZONE ENCODE az64
,customer_uniqueid INTEGER ENCODE az64
,status VARCHAR(1020) ENCODE lzo
,entitytypecd VARCHAR(1020) ENCODE lzo
,first_name VARCHAR(255) ENCODE lzo
,last_name VARCHAR(255) ENCODE lzo
,commercialname VARCHAR(255) ENCODE lzo
,dob TIMESTAMP WITHOUT TIME ZONE ENCODE az64
,gender VARCHAR(10) ENCODE lzo
,maritalstatus VARCHAR(255) ENCODE lzo
,address1 VARCHAR(255) ENCODE lzo
,address2 VARCHAR(255) ENCODE lzo
,county VARCHAR(255) ENCODE lzo
,city VARCHAR(255) ENCODE lzo
,state VARCHAR(255) ENCODE lzo
,postalcode VARCHAR(255) ENCODE lzo
,phone VARCHAR(255) ENCODE lzo
,mobile VARCHAR(255) ENCODE lzo
,email VARCHAR(255) ENCODE lzo
,preferreddeliverymethod VARCHAR(1020) ENCODE lzo
,portalinvitationsentdt DATE ENCODE az64
,paymentreminderind VARCHAR(512) ENCODE lzo
,changedate DATE ENCODE az64
)
DISTSTYLE AUTO
SORTKEY (
customer_id
)
;

DROP TABLE IF EXISTS kdlab.dim_policytransactionextension;
CREATE TABLE kdlab.dim_policytransactionextension
( policytransactionextension_id INTEGER NOT NULL GENERATED BY DEFAULT AS identity(0,1) ENCODE RAW
,loaddate TIMESTAMP WITHOUT TIME ZONE ENCODE az64
,policy_id INTEGER ENCODE az64
,systemid INTEGER ENCODE az64
,bookdt TIMESTAMP WITHOUT TIME ZONE ENCODE az64
,transactioneffectivedt TIMESTAMP WITHOUT TIME ZONE ENCODE az64
,policy_uniqueid INTEGER ENCODE az64
,policytransaction_uniqueid VARCHAR(23) ENCODE lzo
,transactionnumber INTEGER ENCODE az64
,transactioncd VARCHAR(255) ENCODE lzo
,transactionlongdescription VARCHAR(512) ENCODE lzo
,transactionshortdescription VARCHAR(255) ENCODE lzo
,canceltypecd VARCHAR(255) ENCODE lzo
,cancelrequestedbycd VARCHAR(255) ENCODE lzo
,cancelreason VARCHAR(35) ENCODE lzo
)
DISTSTYLE KEY
DISTKEY (systemid)
SORTKEY (
systemid
)
;

DROP TABLE IF EXISTS kdlab.dim_address;									
CREATE TABLE kdlab.dim_address									
(									
address_id INTEGER NOT NULL GENERATED BY DEFAULT AS identity(0,1) ENCODE RAW									
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64									
,address1 VARCHAR(150) NOT NULL ENCODE lzo									
,address2 VARCHAR(150) NOT NULL ENCODE lzo									
,county VARCHAR(50) NOT NULL ENCODE lzo									
,city VARCHAR(50) NOT NULL ENCODE lzo									
,state VARCHAR(50) NOT NULL ENCODE lzo									
,postalcode VARCHAR(20) NOT NULL ENCODE lzo									
,PRIMARY KEY (address_id)									
)									
DISTSTYLE ALL									
SORTKEY (									
address_id									
)									
;									

DROP TABLE IF EXISTS kdlab.dim_company;									
CREATE TABLE kdlab.dim_company									
(									
company_id INTEGER NOT NULL GENERATED BY DEFAULT AS identity(0,1) ENCODE RAW									
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64									
,company_uniqueid VARCHAR(100) NOT NULL ENCODE lzo									
,carriercd VARCHAR(10) NOT NULL ENCODE lzo									
,companycd VARCHAR(10) NOT NULL ENCODE lzo									
,PRIMARY KEY (company_id)									
)									
DISTSTYLE ALL									
SORTKEY (									
company_id									
)									
;									

DROP TABLE IF EXISTS kdlab.dim_deductible;
CREATE TABLE kdlab.dim_deductible
(
deductible_id INTEGER NOT NULL GENERATED BY DEFAULT AS identity(0,1) ENCODE RAW
,loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,cov_deductible1 VARCHAR(255) NOT NULL ENCODE lzo
,cov_deductible2 VARCHAR(255) NOT NULL ENCODE lzo
,cov_deductible1_value NUMERIC(13,2) NOT NULL ENCODE az64
,cov_deductible2_value NUMERIC(13,2) NOT NULL ENCODE az64
,PRIMARY KEY (deductible_id)
)
DISTSTYLE AUTO
SORTKEY (
deductible_id
)
;

DROP TABLE IF EXISTS kdlab.fact_policytransaction;
CREATE TABLE IF NOT EXISTS kdlab.fact_policytransaction
(
loaddate TIMESTAMP WITHOUT TIME ZONE ENCODE az64
,policy_id INTEGER ENCODE az64
,systemid INTEGER ENCODE RAW
,transactiondate_id INTEGER ENCODE az64
,effectivedate_id INTEGER ENCODE az64
,accountingdate_id INTEGER ENCODE az64
,policytransaction_uniqueid VARCHAR(100) ENCODE lzo
,transactionsequence INTEGER ENCODE az64
,transactioncd VARCHAR(50) ENCODE lzo
,policytransactiontype_id INTEGER ENCODE az64
,company_id INTEGER ENCODE az64
,product_id INTEGER ENCODE az64
,firstinsured_id INTEGER ENCODE az64
,coverage_id INTEGER ENCODE az64
,limit_id INTEGER ENCODE az64
,deductible_id INTEGER ENCODE az64
,primaryrisk_id INTEGER ENCODE az64
,building_id INTEGER ENCODE az64
,vehicle_id INTEGER ENCODE az64
,driver_id INTEGER ENCODE az64
,primaryriskaddress_id INTEGER ENCODE az64
,class_id INTEGER ENCODE az64
,producer_id INTEGER ENCODE az64
,policyneworrenewal VARCHAR(7) ENCODE lzo
,policytransactionextension_id INTEGER ENCODE az64
,amount NUMERIC(28,6) ENCODE az64
,term_amount NUMERIC(28,6) ENCODE az64
,commission_amount NUMERIC(28,6) ENCODE az64
,policy_uniqueid INTEGER NOT NULL ENCODE az64
,coverage_uniqueid VARCHAR(1000) NOT NULL ENCODE lzo
)
DISTSTYLE AUTO
DISTKEY (systemid)
SORTKEY (
systemid
)
;

DROP TABLE IF EXISTS kdlab.fact_policycoverage;
CREATE TABLE  kdlab.fact_policycoverage
(
 loaddate TIMESTAMP WITHOUT TIME ZONE NOT NULL ENCODE az64
,month_id INTEGER NOT NULL ENCODE RAW
,policy_id INTEGER NOT NULL ENCODE az64
,systemid INTEGER NOT NULL ENCODE az64
,producer_id INTEGER NOT NULL ENCODE az64
,product_id INTEGER NOT NULL ENCODE az64
,company_id INTEGER NOT NULL ENCODE az64
,firstinsured_id INTEGER NOT NULL ENCODE az64
,policystatus_id INTEGER NOT NULL ENCODE az64
,coverage_id INTEGER NOT NULL ENCODE az64
,limit_id INTEGER NOT NULL ENCODE az64
,deductible_id INTEGER NOT NULL ENCODE az64
,class_id INTEGER NOT NULL ENCODE az64
,primaryrisk_id INTEGER NOT NULL ENCODE az64
,building_id INTEGER NOT NULL ENCODE az64
,vehicle_id INTEGER NOT NULL ENCODE az64
,driver_id INTEGER NOT NULL ENCODE az64
,primaryriskaddress_id INTEGER NOT NULL ENCODE az64
,policyneworrenewal VARCHAR(10) NOT NULL ENCODE lzo
,policynewissuedind INTEGER NOT NULL ENCODE az64
,policycancelledissuedind INTEGER NOT NULL ENCODE az64
,policycancelledeffectiveind INTEGER NOT NULL ENCODE az64
,policyexpiredeffectiveind INTEGER NOT NULL ENCODE az64
,risk_deletedindicator VARCHAR(1) NOT NULL ENCODE lzo
,policy_uniqueid INTEGER NOT NULL ENCODE az64
,coverage_uniqueid VARCHAR(1000) ENCODE lzo
,comm_amt NUMERIC(13,2) NOT NULL ENCODE az64
,comm_amt_ytd NUMERIC(13,2) NOT NULL ENCODE az64
,comm_amt_itd NUMERIC(13,2) NOT NULL ENCODE az64
,wrtn_prem_amt NUMERIC(13,2) NOT NULL ENCODE az64
,wrtn_prem_amt_ytd NUMERIC(13,2) NOT NULL ENCODE az64
,wrtn_prem_amt_itd NUMERIC(13,2) NOT NULL ENCODE az64
,term_prem_amt NUMERIC(13,2) NOT NULL ENCODE az64
,term_prem_amt_ytd NUMERIC(13,2) NOT NULL ENCODE az64
,term_prem_amt_itd NUMERIC(13,2) NOT NULL ENCODE az64
,earned_prem_amt NUMERIC(13,2) NOT NULL ENCODE az64
,earned_prem_amt_ytd NUMERIC(13,2) NOT NULL ENCODE az64
,earned_prem_amt_itd NUMERIC(13,2) NOT NULL ENCODE az64
,spinn_earned_prem_amt NUMERIC(13,2) NOT NULL ENCODE az64
,spinn_earned_prem_amt_ytd NUMERIC(13,2) NOT NULL ENCODE az64
,spinn_earned_prem_amt_itd NUMERIC(13,2) NOT NULL ENCODE az64
,unearned_prem NUMERIC(13,2) NOT NULL ENCODE az64
,spinn_unearned_prem NUMERIC(13,2) NOT NULL ENCODE az64
,comm_earned_amt NUMERIC(13,2) NOT NULL ENCODE az64
,comm_earned_amt_ytd NUMERIC(13,2) NOT NULL ENCODE az64
,comm_earned_amt_itd NUMERIC(13,2) NOT NULL ENCODE az64
,cncl_prem_amt NUMERIC(13,2) NOT NULL ENCODE az64
,cncl_prem_amt_ytd NUMERIC(13,2) NOT NULL ENCODE az64
,cncl_prem_amt_itd NUMERIC(13,2) NOT NULL ENCODE az64
,fees_amt NUMERIC(13,2) NOT NULL ENCODE az64
,fees_amt_ytd NUMERIC(13,2) NOT NULL ENCODE az64
,fees_amt_itd NUMERIC(13,2) NOT NULL ENCODE az64
,wrtn_exposures INTEGER ENCODE az64
,wrtn_exposures_ytd INTEGER ENCODE az64
,wrtn_exposures_itd INTEGER ENCODE az64
,earned_exposures NUMERIC(38,4) ENCODE az64
,earned_exposures_ytd NUMERIC(38,4) ENCODE az64
,earned_exposures_itd NUMERIC(38,4) ENCODE az64
)
DISTSTYLE AUTO
DISTKEY (systemid)
SORTKEY (
month_id
)
;

