CREATE NONCLUSTERED INDEX [IDX_DIM_ADDRESS] ON [dbo].[DIM_ADDRESS]
(	
	[ADDRESS1] ASC,
	[ADDRESS2] ASC,
	[COUNTY] ASC,
	[CITY] ASC,
	[STATE] ASC,
	[POSTALCODE] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([ADDRESS_ID])
;


CREATE NONCLUSTERED INDEX [IDX_DIM_ADJUSTER] ON [dbo].[DIM_ADJUSTER]
(	
	[ADJUSTER_UNIQUEID] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([ADJUSTER_ID])
;





CREATE NONCLUSTERED INDEX [IDX_DIM_CLAIM] ON [dbo].[DIM_CLAIM]
(
	[CLAIM_UNIQUEID] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([CLAIM_ID],[CLAIMNUMBER])
;

CREATE NONCLUSTERED INDEX [IDX_DIM_CLAIMANT] ON [dbo].[DIM_CLAIMANT]
(
	[CLAIMANT_UNIQUEID] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([CLAIMANT_ID])
;

CREATE NONCLUSTERED INDEX [IDX_DIM_COVEREDRISK] ON [dbo].[DIM_COVEREDRISK]
(
	[RISK_UNIQUEID] ASC,
	[SYSTEMID] ASC,
	[POLICY_UNIQUEID] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([COVEREDRISK_ID],[RISK_TYPE])
;

CREATE NONCLUSTERED INDEX [IDX_DIM_DEDUCTIBLE] ON [dbo].[DIM_DEDUCTIBLE]
(
	[COV_DEDUCTIBLE1] ASC,
	[COV_DEDUCTIBLE2] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([DEDUCTIBLE_ID])
;


CREATE NONCLUSTERED INDEX [IDX_DIM_DRIVER] ON [dbo].[DIM_DRIVER]
(	
	[DRIVER_UNIQUEID] ASC,
	[SYSTEMID] ASC,
	[POLICY_UNIQUEID] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([DRIVER_ID])
;



CREATE NONCLUSTERED INDEX [IDX_DIM_LIMIT] ON [dbo].[DIM_LIMIT]
(
	[COV_LIMIT1] ASC,
	[COV_LIMIT2] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([LIMIT_ID])
;


CREATE NONCLUSTERED INDEX [IDX_DIM_POLICYTRANSACTIONEXTENSION] ON [dbo].[DIM_POLICYTRANSACTIONEXTENSION]
(	
	[SYSTEMID] ASC,
	[POLICY_UNIQUEID] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([POLICYTRANSACTIONEXTENSION_ID])
;

CREATE NONCLUSTERED INDEX [IDX_DIM_PRODUCER] ON [dbo].[DIM_PRODUCER]
(	
	[PRODUCER_UNIQUEID] ASC,
	[SOURCE_SYSTEM] ASC
)
INCLUDE([PRODUCER_ID])
;