IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_ADDRESS')
            AND   NAME  = 'IDX_DIM_ADDRESS'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_ADDRESS.IDX_DIM_ADDRESS;




IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_ADJUSTER')
            AND   NAME  = 'IDX_DIM_ADJUSTER'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_ADJUSTER.IDX_DIM_ADJUSTER;



IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_CLAIM')
            AND   NAME  = 'IDX_DIM_CLAIM'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_CLAIM.IDX_DIM_CLAIM;


IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_CLAIMANT')
            AND   NAME  = 'IDX_DIM_CLAIMANT'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_CLAIMANT.IDX_DIM_CLAIMANT;


IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_COVEREDRISK')
            AND   NAME  = 'IDX_DIM_COVEREDRISK'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_COVEREDRISK.IDX_DIM_COVEREDRISK;

IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_DEDUCTIBLE')
            AND   NAME  = 'IDX_DIM_DEDUCTIBLE'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_DEDUCTIBLE.IDX_DIM_DEDUCTIBLE;


IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_DRIVER')
            AND   NAME  = 'IDX_DIM_DRIVER'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_DRIVER.IDX_DIM_DRIVER;


IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_LIMIT')
            AND   NAME  = 'IDX_DIM_LIMIT'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_LIMIT.IDX_DIM_LIMIT;


IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_POLICYTRANSACTIONEXTENSION')
            AND   NAME  = 'IDX_DIM_POLICYTRANSACTIONEXTENSION'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_POLICYTRANSACTIONEXTENSION.IDX_DIM_POLICYTRANSACTIONEXTENSION;


IF EXISTS (SELECT 1
            FROM  SYSINDEXES
           WHERE  ID    = OBJECT_ID('DIM_PRODUCER')
            AND   NAME  = 'IDX_DIM_PRODUCER'
            AND   INDID > 0
            AND   INDID < 255)
   DROP INDEX DIM_PRODUCER.IDX_DIM_PRODUCER;
